/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/_root'
import { Route as appRouteImport } from './routes/_app'
import { Route as authAuthRouteImport } from './routes/auth/_auth'
import { Route as indexRouteImport } from './routes/index'
import { Route as authSinginRouteImport } from './routes/auth/singin'
import { Route as authSingupRouteImport } from './routes/auth/singup'

const appRoute = appRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRoute,
} as any)
const authSinginRoute = authSinginRouteImport.update({
  id: '/singin',
  path: '/singin',
  getParentRoute: () => authAuthRoute,
} as any)
const authSingupRoute = authSingupRouteImport.update({
  id: '/singup',
  path: '/singup',
  getParentRoute: () => authAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof indexRoute
  '/singin': typeof authSinginRoute
  '/singup': typeof authSingupRoute
}
export interface FileRoutesByTo {
  '/': typeof indexRoute
  '/singin': typeof authSinginRoute
  '/singup': typeof authSingupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof appRouteWithChildren
  '/_auth': typeof authAuthRouteWithChildren
  '/_app/': typeof indexRoute
  '/_auth/singin': typeof authSinginRoute
  '/_auth/singup': typeof authSingupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/singin' | '/singup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/singin' | '/singup'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/'
    | '/_auth/singin'
    | '/_auth/singup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRoute: typeof appRouteWithChildren
  authAuthRoute: typeof authAuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof appRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexRouteImport
      parentRoute: typeof appRoute
    }
    '/_auth/singin': {
      id: '/_auth/singin'
      path: '/singin'
      fullPath: '/singin'
      preLoaderRoute: typeof authSinginRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/_auth/singup': {
      id: '/_auth/singup'
      path: '/singup'
      fullPath: '/singup'
      preLoaderRoute: typeof authSingupRouteImport
      parentRoute: typeof authAuthRoute
    }
  }
}

interface appRouteChildren {
  indexRoute: typeof indexRoute
}

const appRouteChildren: appRouteChildren = {
  indexRoute: indexRoute,
}

const appRouteWithChildren = appRoute._addFileChildren(appRouteChildren)

interface authAuthRouteChildren {
  authSinginRoute: typeof authSinginRoute
  authSingupRoute: typeof authSingupRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authSinginRoute: authSinginRoute,
  authSingupRoute: authSingupRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRoute: appRouteWithChildren,
  authAuthRoute: authAuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
