// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group.sql

package repos

import (
	"context"
)

const addPolicyToGroup = `-- name: AddPolicyToGroup :exec
INSERT INTO group_policy (group_id, policy_id) VALUES (?, ?)
`

type AddPolicyToGroupParams struct {
	GroupID  int64 `json:"group_id"`
	PolicyID int64 `json:"policy_id"`
}

func (q *Queries) AddPolicyToGroup(ctx context.Context, arg AddPolicyToGroupParams) error {
	_, err := q.db.ExecContext(ctx, addPolicyToGroup, arg.GroupID, arg.PolicyID)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, is_system)
VALUES (?, 0)
RETURNING id, name, is_system, created_at, updated_at
`

func (q *Queries) CreateGroup(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPolicy = `-- name: CreatePolicy :one
INSERT INTO policy (action) VALUES (?) RETURNING id, "action", created_at
`

func (q *Queries) CreatePolicy(ctx context.Context, action string) (Policy, error) {
	row := q.db.QueryRowContext(ctx, createPolicy, action)
	var i Policy
	err := row.Scan(&i.ID, &i.Action, &i.CreatedAt)
	return i, err
}

const createSystemGroup = `-- name: CreateSystemGroup :one
INSERT INTO groups (name, is_system)
VALUES (?, 1)
RETURNING id, name, is_system, created_at, updated_at
`

func (q *Queries) CreateSystemGroup(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRowContext(ctx, createSystemGroup, name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = ? AND is_system = 0
`

func (q *Queries) DeleteGroup(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const deletePolicyByID = `-- name: DeletePolicyByID :exec
DELETE FROM policy WHERE id = ?
`

func (q *Queries) DeletePolicyByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePolicyByID, id)
	return err
}

const getAllPolicies = `-- name: GetAllPolicies :many
SELECT id, "action", created_at FROM policy ORDER BY action ASC
`

func (q *Queries) GetAllPolicies(ctx context.Context) ([]Policy, error) {
	rows, err := q.db.QueryContext(ctx, getAllPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(&i.ID, &i.Action, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, is_system, created_at, updated_at FROM groups WHERE id = ?
`

func (q *Queries) GetGroupByID(ctx context.Context, id int64) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupByName = `-- name: GetGroupByName :one
SELECT id, name, is_system, created_at, updated_at FROM groups WHERE name = ? LIMIT 1
`

func (q *Queries) GetGroupByName(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByName, name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupPolicies = `-- name: GetGroupPolicies :many
SELECT p.id, p."action", p.created_at FROM policy p
JOIN group_policy gp ON gp.policy_id = p.id
WHERE gp.group_id = ?
`

func (q *Queries) GetGroupPolicies(ctx context.Context, groupID int64) ([]Policy, error) {
	rows, err := q.db.QueryContext(ctx, getGroupPolicies, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(&i.ID, &i.Action, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFinalPermissions = `-- name: GetUserFinalPermissions :many
WITH user_permissions AS (
    SELECT p.action, up.effect
    FROM user_policy up
    JOIN policy p ON p.id = up.policy_id
    WHERE up.user_id = ?1
      AND up.org_id = ?2
)
SELECT DISTINCT action
FROM (
    SELECT p.action
    FROM group_policy gp
    JOIN policy p ON p.id = gp.policy_id
    JOIN organization_members om
        ON om.group_id = gp.group_id
    WHERE om.user_id = ?1
      AND om.organization_id = ?2

    UNION ALL

    SELECT action
    FROM user_permissions
    WHERE effect = 'GRANT'
) perms
WHERE action NOT IN (
    SELECT action
    FROM user_permissions
    WHERE effect = 'DENY'
)
`

type GetUserFinalPermissionsParams struct {
	UserID int64 `json:"user_id"`
	OrgID  int64 `json:"org_id"`
}

func (q *Queries) GetUserFinalPermissions(ctx context.Context, arg GetUserFinalPermissionsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUserFinalPermissions, arg.UserID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var action string
		if err := rows.Scan(&action); err != nil {
			return nil, err
		}
		items = append(items, action)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, is_system, created_at, updated_at FROM groups ORDER BY created_at ASC
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePolicyFromGroup = `-- name: RemovePolicyFromGroup :exec
DELETE FROM group_policy WHERE group_id = ? AND policy_id = ?
`

type RemovePolicyFromGroupParams struct {
	GroupID  int64 `json:"group_id"`
	PolicyID int64 `json:"policy_id"`
}

func (q *Queries) RemovePolicyFromGroup(ctx context.Context, arg RemovePolicyFromGroupParams) error {
	_, err := q.db.ExecContext(ctx, removePolicyFromGroup, arg.GroupID, arg.PolicyID)
	return err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups SET name = ? WHERE id = ? AND is_system = 0
RETURNING id, name, is_system, created_at, updated_at
`

type UpdateGroupParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, updateGroup, arg.Name, arg.ID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
