// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule.sql

package repos

import (
	"context"
)

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (
    name, description, cron_expression, app_name, service_name,
    shell_type, schedule_type, command, script, timezone, enabled,
    application_id, compose_id, server_id, organization_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, description, cron_expression, app_name, service_name, shell_type, schedule_type, command, script, timezone, enabled, application_id, compose_id, server_id, organization_id, created_at, updated_at
`

type CreateScheduleParams struct {
	Name           string  `json:"name"`
	Description    *string `json:"description"`
	CronExpression string  `json:"cron_expression"`
	AppName        string  `json:"app_name"`
	ServiceName    *string `json:"service_name"`
	ShellType      string  `json:"shell_type"`
	ScheduleType   string  `json:"schedule_type"`
	Command        string  `json:"command"`
	Script         *string `json:"script"`
	Timezone       *string `json:"timezone"`
	Enabled        int64   `json:"enabled"`
	ApplicationID  *int64  `json:"application_id"`
	ComposeID      *int64  `json:"compose_id"`
	ServerID       *int64  `json:"server_id"`
	OrganizationID *int64  `json:"organization_id"`
}

func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, createSchedule,
		arg.Name,
		arg.Description,
		arg.CronExpression,
		arg.AppName,
		arg.ServiceName,
		arg.ShellType,
		arg.ScheduleType,
		arg.Command,
		arg.Script,
		arg.Timezone,
		arg.Enabled,
		arg.ApplicationID,
		arg.ComposeID,
		arg.ServerID,
		arg.OrganizationID,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CronExpression,
		&i.AppName,
		&i.ServiceName,
		&i.ShellType,
		&i.ScheduleType,
		&i.Command,
		&i.Script,
		&i.Timezone,
		&i.Enabled,
		&i.ApplicationID,
		&i.ComposeID,
		&i.ServerID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules WHERE id = ?
`

func (q *Queries) DeleteSchedule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSchedule, id)
	return err
}

const getScheduleByID = `-- name: GetScheduleByID :one
SELECT id, name, description, cron_expression, app_name, service_name, shell_type, schedule_type, command, script, timezone, enabled, application_id, compose_id, server_id, organization_id, created_at, updated_at FROM schedules WHERE id = ?
`

func (q *Queries) GetScheduleByID(ctx context.Context, id int64) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, getScheduleByID, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CronExpression,
		&i.AppName,
		&i.ServiceName,
		&i.ShellType,
		&i.ScheduleType,
		&i.Command,
		&i.Script,
		&i.Timezone,
		&i.Enabled,
		&i.ApplicationID,
		&i.ComposeID,
		&i.ServerID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScheduleWithRelations = `-- name: GetScheduleWithRelations :one
SELECT 
    s.id, s.name, s.description, s.cron_expression, s.app_name, s.service_name, s.shell_type, s.schedule_type, s.command, s.script, s.timezone, s.enabled, s.application_id, s.compose_id, s.server_id, s.organization_id, s.created_at, s.updated_at,
    a.app_name AS application_app_name,
    a.server_id AS application_server_id,
    c.app_name AS compose_app_name,
    c.server_id AS compose_server_id,
    srv.name AS server_name
FROM schedules s
LEFT JOIN applications a ON s.application_id = a.id
LEFT JOIN compose_projects c ON s.compose_id = c.id
LEFT JOIN servers srv ON s.server_id = srv.id
WHERE s.id = ?
`

type GetScheduleWithRelationsRow struct {
	ID                  int64   `json:"id"`
	Name                string  `json:"name"`
	Description         *string `json:"description"`
	CronExpression      string  `json:"cron_expression"`
	AppName             string  `json:"app_name"`
	ServiceName         *string `json:"service_name"`
	ShellType           string  `json:"shell_type"`
	ScheduleType        string  `json:"schedule_type"`
	Command             string  `json:"command"`
	Script              *string `json:"script"`
	Timezone            *string `json:"timezone"`
	Enabled             int64   `json:"enabled"`
	ApplicationID       *int64  `json:"application_id"`
	ComposeID           *int64  `json:"compose_id"`
	ServerID            *int64  `json:"server_id"`
	OrganizationID      *int64  `json:"organization_id"`
	CreatedAt           int64   `json:"created_at"`
	UpdatedAt           int64   `json:"updated_at"`
	ApplicationAppName  *string `json:"application_app_name"`
	ApplicationServerID *int64  `json:"application_server_id"`
	ComposeAppName      *string `json:"compose_app_name"`
	ComposeServerID     *int64  `json:"compose_server_id"`
	ServerName          *string `json:"server_name"`
}

func (q *Queries) GetScheduleWithRelations(ctx context.Context, id int64) (GetScheduleWithRelationsRow, error) {
	row := q.db.QueryRowContext(ctx, getScheduleWithRelations, id)
	var i GetScheduleWithRelationsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CronExpression,
		&i.AppName,
		&i.ServiceName,
		&i.ShellType,
		&i.ScheduleType,
		&i.Command,
		&i.Script,
		&i.Timezone,
		&i.Enabled,
		&i.ApplicationID,
		&i.ComposeID,
		&i.ServerID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ApplicationAppName,
		&i.ApplicationServerID,
		&i.ComposeAppName,
		&i.ComposeServerID,
		&i.ServerName,
	)
	return i, err
}

const getServerWithSSHKey = `-- name: GetServerWithSSHKey :one
SELECT 
    s.id,
    s.name,
    s.ip_address,
    s.port,
    s.username,
    k.private_key
FROM servers s
LEFT JOIN ssh_keys k ON s.ssh_key_id = k.id
WHERE s.id = ?
`

type GetServerWithSSHKeyRow struct {
	ID         int64   `json:"id"`
	Name       string  `json:"name"`
	IpAddress  string  `json:"ip_address"`
	Port       int64   `json:"port"`
	Username   string  `json:"username"`
	PrivateKey *string `json:"private_key"`
}

func (q *Queries) GetServerWithSSHKey(ctx context.Context, id int64) (GetServerWithSSHKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getServerWithSSHKey, id)
	var i GetServerWithSSHKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IpAddress,
		&i.Port,
		&i.Username,
		&i.PrivateKey,
	)
	return i, err
}

const listEnabledSchedules = `-- name: ListEnabledSchedules :many
SELECT 
    s.id, s.name, s.description, s.cron_expression, s.app_name, s.service_name, s.shell_type, s.schedule_type, s.command, s.script, s.timezone, s.enabled, s.application_id, s.compose_id, s.server_id, s.organization_id, s.created_at, s.updated_at,
    a.app_name AS application_app_name,
    a.server_id AS application_server_id,
    c.app_name AS compose_app_name,
    c.server_id AS compose_server_id,
    srv.name AS server_name
FROM schedules s
LEFT JOIN applications a ON s.application_id = a.id
LEFT JOIN compose_projects c ON s.compose_id = c.id
LEFT JOIN servers srv ON s.server_id = srv.id
WHERE s.enabled = 1
`

type ListEnabledSchedulesRow struct {
	ID                  int64   `json:"id"`
	Name                string  `json:"name"`
	Description         *string `json:"description"`
	CronExpression      string  `json:"cron_expression"`
	AppName             string  `json:"app_name"`
	ServiceName         *string `json:"service_name"`
	ShellType           string  `json:"shell_type"`
	ScheduleType        string  `json:"schedule_type"`
	Command             string  `json:"command"`
	Script              *string `json:"script"`
	Timezone            *string `json:"timezone"`
	Enabled             int64   `json:"enabled"`
	ApplicationID       *int64  `json:"application_id"`
	ComposeID           *int64  `json:"compose_id"`
	ServerID            *int64  `json:"server_id"`
	OrganizationID      *int64  `json:"organization_id"`
	CreatedAt           int64   `json:"created_at"`
	UpdatedAt           int64   `json:"updated_at"`
	ApplicationAppName  *string `json:"application_app_name"`
	ApplicationServerID *int64  `json:"application_server_id"`
	ComposeAppName      *string `json:"compose_app_name"`
	ComposeServerID     *int64  `json:"compose_server_id"`
	ServerName          *string `json:"server_name"`
}

func (q *Queries) ListEnabledSchedules(ctx context.Context) ([]ListEnabledSchedulesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledSchedulesRow{}
	for rows.Next() {
		var i ListEnabledSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CronExpression,
			&i.AppName,
			&i.ServiceName,
			&i.ShellType,
			&i.ScheduleType,
			&i.Command,
			&i.Script,
			&i.Timezone,
			&i.Enabled,
			&i.ApplicationID,
			&i.ComposeID,
			&i.ServerID,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApplicationAppName,
			&i.ApplicationServerID,
			&i.ComposeAppName,
			&i.ComposeServerID,
			&i.ServerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchedule = `-- name: UpdateSchedule :one
UPDATE schedules
SET 
    name = ?,
    description = ?,
    cron_expression = ?,
    service_name = ?,
    shell_type = ?,
    schedule_type = ?,
    command = ?,
    script = ?,
    timezone = ?,
    enabled = ?,
    application_id = ?,
    compose_id = ?,
    server_id = ?,
    organization_id = ?,
    updated_at = (strftime('%s', 'now'))
WHERE id = ?
RETURNING id, name, description, cron_expression, app_name, service_name, shell_type, schedule_type, command, script, timezone, enabled, application_id, compose_id, server_id, organization_id, created_at, updated_at
`

type UpdateScheduleParams struct {
	Name           string  `json:"name"`
	Description    *string `json:"description"`
	CronExpression string  `json:"cron_expression"`
	ServiceName    *string `json:"service_name"`
	ShellType      string  `json:"shell_type"`
	ScheduleType   string  `json:"schedule_type"`
	Command        string  `json:"command"`
	Script         *string `json:"script"`
	Timezone       *string `json:"timezone"`
	Enabled        int64   `json:"enabled"`
	ApplicationID  *int64  `json:"application_id"`
	ComposeID      *int64  `json:"compose_id"`
	ServerID       *int64  `json:"server_id"`
	OrganizationID *int64  `json:"organization_id"`
	ID             int64   `json:"id"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error) {
	row := q.db.QueryRowContext(ctx, updateSchedule,
		arg.Name,
		arg.Description,
		arg.CronExpression,
		arg.ServiceName,
		arg.ShellType,
		arg.ScheduleType,
		arg.Command,
		arg.Script,
		arg.Timezone,
		arg.Enabled,
		arg.ApplicationID,
		arg.ComposeID,
		arg.ServerID,
		arg.OrganizationID,
		arg.ID,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CronExpression,
		&i.AppName,
		&i.ServiceName,
		&i.ShellType,
		&i.ScheduleType,
		&i.Command,
		&i.Script,
		&i.Timezone,
		&i.Enabled,
		&i.ApplicationID,
		&i.ComposeID,
		&i.ServerID,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
